### ISSUE TITLE
Unable to provide MFA Token

### ISSUE THREAD

**Issue by KushalP** [piontas/python-aada#10]
When trying to login, it fails to ask me for the MFA token and then exits with the following stacktrace:

```
ᐅ aada login
Azure username: redacted@example.com
Azure password:
Azure MFA Token: Traceback (most recent call last):
  File "/usr/local/bin/aada", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/aada/cli.py", line 84, in main
    return cli.main()
  File "/usr/local/lib/python3.7/site-packages/aada/cli.py", line 79, in main
    return self.__getattribute__('_{}'.format(self._parsed_args.command))()
  File "/usr/local/lib/python3.7/site-packages/aada/cli.py", line 52, in _login
    return login()
  File "/usr/local/lib/python3.7/site-packages/aada/login.py", line 82, in __call__
    return self._login()
  File "/usr/local/lib/python3.7/site-packages/aada/login.py", line 285, in _login
    url, username_input, password_input, self._azure_mfa))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/aada/login.py", line 163, in _render_js_form
    mfa_token = input('Azure MFA Token: ')
EOFError: EOF when reading a line
```

**Comment by KushalP** [comment]
Resetting my terminal appears to have fixed the above issue.
