### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'newPage' on login

### ISSUE THREAD

**Issue by xyjrshank** [piontas/python-aada#2]
**Steps to reproduce**

1. Set up profile
2. Run: aada login --profile _profile_name_
3. Enter Azure password

**Result**

`Traceback (most recent call last):
  File "/usr/bin/aada", line 11, in <module>
    load_entry_point('aada==0.1.3', 'console_scripts', 'aada')()
  File "/usr/lib/python3.6/dist-packages/aada/cli.py", line 70, in main
    return cli.main()
  File "/usr/lib/python3.6/dist-packages/aada/cli.py", line 65, in main
    return self.__getattribute__('_{}'.format(self._parsed_args.command))()
  File "/usr/lib/python3.6/dist-packages/aada/cli.py", line 45, in _login
    return login()
  File "/usr/lib/python3.6/dist-packages/aada/login.py", line 65, in __call__
    return self._login()
  File "/usr/lib/python3.6/dist-packages/aada/login.py", line 224, in _login
    self._azure_mfa))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/dist-packages/aada/login.py", line 100, in _render_js_form
    page = await browser.newPage()
AttributeError: 'coroutine' object has no attribute 'newPage'
sys:1: RuntimeWarning: coroutine 'Launcher.launch' was never awaited`

**Environment**

- Amazon Linux 2017.09
- Python 3.2.6
- Installed packages:
aada==0.1.3
awscli==1.14.54
boto==2.48.0
boto3==1.6.7
botocore==1.9.7
certifi==2018.1.18
chardet==3.0.4
colorama==0.3.7
docutils==0.14
idna==2.6
jmespath==0.9.3
jprops==2.0.2
lxml==4.1.1
pimento==0.7.1
pkgconfig==1.3.1
pyasn1==0.4.2
pyee==5.0.0
pyppeteer==0.0.13
python-dateutil==2.7.0
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.13
saml==0.9.0
six==1.11.0
untangle==1.1.1
urllib3==1.22
virtualenv==15.1.0
websockets==4.0.1
xmlsec==1.3.3

**Comment by fvant** [comment]
I am using pyppeteer 0.0.9  and that works for me..perhaps worth downgrading ?

**Comment by xyjrshank** [comment]
That helped a bit. After downgrading pyppeteer, running login resulted in:

`pkg_resources.DistributionNotFound: The 'python-dateutil<2.7.0,>=2.1' distribution was not found and is required by botocore`

I downgraded python-dateutil to 2.6.1 and now when I run login I get:

`Traceback (most recent call last):
  File "/usr/bin/aada", line 11, in <module>
    load_entry_point('aada==0.1.3', 'console_scripts', 'aada')()
  File "/usr/lib/python3.6/dist-packages/aada/cli.py", line 70, in main
    return cli.main()
  File "/usr/lib/python3.6/dist-packages/aada/cli.py", line 65, in main
    return self.__getattribute__('_{}'.format(self._parsed_args.command))()
  File "/usr/lib/python3.6/dist-packages/aada/cli.py", line 45, in _login
    return login()
  File "/usr/lib/python3.6/dist-packages/aada/login.py", line 65, in __call__
    return self._login()
  File "/usr/lib/python3.6/dist-packages/aada/login.py", line 224, in _login
    self._azure_mfa))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/dist-packages/aada/login.py", line 98, in _render_js_form
    args=['--no-sandbox', '--disable-setuid-sandbox'])
  File "/usr/lib/python3.6/dist-packages/aada/launcher.py", line 46, in launch
    return HeadLessLauncher(options, **kwargs).launch()
  File "/usr/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 109, in launch
    raise BrowserError('Unexpectedly chrome process closed with '
pyppeteer.errors.BrowserError: Unexpectedly chrome process closed with return code: 127`

**Comment by xyjrshank** [comment]
It looks like the Chrome binary that pyppeteer downloaded doesn't run well on Amazon Linux. Luckily, the binary from https://github.com/danielsantiago/puppeteer-lambda-starter-kit/blob/master/chrome/HeadlessChrome-66.0.3343.0.tar.gz is compatible. Now I'm just getting:

`Please try again, probably you entered a wrong password/token
waiting failed: timeout 30000ms exceeded`

I'm confident that I'm using correct credentials. What is the best way to debug?

**Comment by fvant** [comment]
did you try the kmsi  option ?  for keep me signed in popup that might be in the way ?

**Comment by xyjrshank** [comment]
I just set `azure_kmsi = True` and tried again. Same result.

**Comment by xyjrshank** [comment]
I'm now intermittently getting:
`Traceback (most recent call last):
  File "/usr/bin/aada", line 11, in <module>
    load_entry_point('aada==0.1.3', 'console_scripts', 'aada')()
  File "/usr/lib/python3.6/dist-packages/aada/cli.py", line 70, in main
    return cli.main()
  File "/usr/lib/python3.6/dist-packages/aada/cli.py", line 65, in main
    return self.__getattribute__('_{}'.format(self._parsed_args.command))()
  File "/usr/lib/python3.6/dist-packages/aada/cli.py", line 45, in _login
    return login()
  File "/usr/lib/python3.6/dist-packages/aada/login.py", line 65, in __call__
    return self._login()
  File "/usr/lib/python3.6/dist-packages/aada/login.py", line 224, in _login
    self._azure_mfa))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/dist-packages/aada/login.py", line 141, in _render_js_form
    await page.querySelector('input[name="SAMLResponse"]')
  File "/usr/lib/python3.6/dist-packages/pyppeteer/page.py", line 169, in querySelector
    return await frame.querySelector(selector)
  File "/usr/lib/python3.6/dist-packages/pyppeteer/frame_manager.py", line 166, in querySelector
    'selector => document.querySelector(selector)', selector)
  File "/usr/lib/python3.6/dist-packages/pyppeteer/frame_manager.py", line 221, in _rawEvaluate
    'awaitPromise': True,
  File "/usr/lib/python3.6/dist-packages/pyppeteer/connection.py", line 176, in send
    return await callback
pyppeteer.errors.NetworkError: Protocol Error: Cannot find context with specified id None`

**Comment by piontas** [comment]
Please try with the newest version `aada==0.1.6`
